@startuml
title DER - Sistema de Vendas Online
hide methods
hide stereotypes
skinparam linetype ortho
skinparam entity {
  BackgroundColor #F8FAFC
  BorderColor #334155
  FontColor #0F172A
}

entity "ATS_CLIENTE" as cliente {
  * cliente_id : NUMBER <<PK>>
  --
  * nome : VARCHAR2(100) <<NN>>
  * email : VARCHAR2(150) <<UK, NN>>
  telefone : VARCHAR2(11)
  * data_nascimento : DATE <<NN>>
  * status_cliente : CHAR(1) <<CK>>
}

entity "ATS_ENDERECO" as endereco {
  * endereco_id : NUMBER <<PK>>
  --
  * cliente_id : NUMBER <<FK, NN>>
  * tipo_endereco : VARCHAR2(12) <<CK>>
  * logradouro : VARCHAR2(150) <<NN>>
  * numero : NUMBER <<CK>>
  complemento : VARCHAR2(60)
  * cep : CHAR(8) <<CK>>
  * cidade : VARCHAR2(80) <<NN>>
  * uf : CHAR(2) <<CK>>
}

entity "ATS_CATEGORIA" as categoria {
  * categoria_id : NUMBER <<PK>>
  --
  * nome : VARCHAR2(80) <<UK, NN>>
  descricao : VARCHAR2(250)
  * ativo : CHAR(1) <<CK>>
}

entity "ATS_PRODUTO" as produto {
  * produto_id : NUMBER <<PK>>
  --
  * categoria_id : NUMBER <<FK, NN>>
  * sku : VARCHAR2(20) <<UK, NN>>
  * nome : VARCHAR2(120) <<NN>>
  * preco : NUMBER(12,2) <<CK>>
  * estoque : NUMBER(8) <<CK>>
  * ativo : CHAR(1) <<CK>>
}

entity "ATS_PEDIDO" as pedido {
  * pedido_id : NUMBER <<PK>>
  --
  * cliente_id : NUMBER <<FK, NN>>
  * endereco_id : NUMBER <<FK, NN>>
  * data_pedido : DATE <<NN>>
  * status_pedido : VARCHAR2(12) <<CK>>
  * valor_total : NUMBER(12,2) <<CK>>
}

entity "ATS_ITEM_PEDIDO" as item {
  * pedido_id : NUMBER <<PK, FK>>
  * produto_id : NUMBER <<PK, FK>>
  --
  * quantidade : NUMBER(3) <<CK>>
  * preco_unitario : NUMBER(12,2) <<CK>>
  * desconto_percentual : NUMBER(5,2) <<CK>>
}

entity "ATS_PAGAMENTO" as pagamento {
  * pagamento_id : NUMBER <<PK>>
  --
  * pedido_id : NUMBER <<FK, UK, NN>>
  * forma_pagamento : VARCHAR2(12) <<CK>>
  * valor : NUMBER(12,2) <<CK>>
  * parcelas : NUMBER(2) <<CK>>
  * status_pagamento : VARCHAR2(12) <<CK>>
  * data_pagamento : DATE <<NN>>
}

entity "ATS_ENTREGA" as entrega {
  * entrega_id : NUMBER <<PK>>
  --
  * pedido_id : NUMBER <<FK, UK, NN>>
  * transportadora : VARCHAR2(80) <<NN>>
  codigo_rastreio : VARCHAR2(40) <<UK>>
  * status_entrega : VARCHAR2(12) <<CK>>
  data_envio : DATE
  data_prevista : DATE
  data_entrega : DATE
}

cliente ||--o{ endereco : possui
cliente ||--o{ pedido : realiza
endereco ||--o{ pedido : recebe
categoria ||--o{ produto : classifica
pedido ||--|{ item : contém
produto ||--o{ item : compõe
pedido ||--o| pagamento : é pago por
pedido ||--o| entrega : gera
@enduml