-- Arquivo: 01_criar_tabelas.sql
-- Finalidade: criar as oito tabelas do DER e todas as restrições de integridade do sistema de vendas.
-- Uso: executar após 00_limpeza.sql no usuário Oracle da atividade.

SET ECHO ON
SET FEEDBACK ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE TABLE ats_cliente (
  cliente_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome             VARCHAR2(100) NOT NULL,
  email            VARCHAR2(150) NOT NULL,
  telefone         VARCHAR2(11),
  data_nascimento  DATE NOT NULL,
  status_cliente   CHAR(1) DEFAULT 'A' NOT NULL,
  CONSTRAINT pk_ats_cliente PRIMARY KEY (cliente_id),
  CONSTRAINT uk_ats_cliente_email UNIQUE (email),
  CONSTRAINT ck_ats_cliente_nome CHECK (LENGTH(TRIM(nome)) BETWEEN 3 AND 100),
  CONSTRAINT ck_ats_cliente_email CHECK (REGEXP_LIKE(email, '^[^@ ]+@[^@ ]+[.][^@ ]+$')),
  CONSTRAINT ck_ats_cliente_tel CHECK (telefone IS NULL OR REGEXP_LIKE(telefone, '^[0-9]{10,11}$')),
  CONSTRAINT ck_ats_cliente_nasc CHECK (data_nascimento BETWEEN DATE '1900-01-01' AND DATE '2008-09-26'),
  CONSTRAINT ck_ats_cliente_status CHECK (status_cliente IN ('A', 'I'))
);

CREATE TABLE ats_endereco (
  endereco_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cliente_id     NUMBER NOT NULL,
  tipo_endereco  VARCHAR2(12) NOT NULL,
  logradouro     VARCHAR2(150) NOT NULL,
  numero         NUMBER(6) NOT NULL,
  complemento    VARCHAR2(60),
  cep            CHAR(8) NOT NULL,
  cidade         VARCHAR2(80) NOT NULL,
  uf             CHAR(2) NOT NULL,
  CONSTRAINT pk_ats_endereco PRIMARY KEY (endereco_id),
  CONSTRAINT uk_ats_endereco_cli UNIQUE (endereco_id, cliente_id),
  CONSTRAINT fk_ats_endereco_cliente FOREIGN KEY (cliente_id) REFERENCES ats_cliente (cliente_id),
  CONSTRAINT ck_ats_endereco_tipo CHECK (tipo_endereco IN ('RESIDENCIAL', 'COMERCIAL')),
  CONSTRAINT ck_ats_endereco_logr CHECK (LENGTH(TRIM(logradouro)) BETWEEN 3 AND 150),
  CONSTRAINT ck_ats_endereco_num CHECK (numero BETWEEN 1 AND 999999 AND numero = TRUNC(numero)),
  CONSTRAINT ck_ats_endereco_cep CHECK (REGEXP_LIKE(cep, '^[0-9]{8}$')),
  CONSTRAINT ck_ats_endereco_uf CHECK (REGEXP_LIKE(uf, '^[A-Z]{2}$'))
);

CREATE TABLE ats_categoria (
  categoria_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nome          VARCHAR2(80) NOT NULL,
  descricao     VARCHAR2(250),
  ativo         CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_ats_categoria PRIMARY KEY (categoria_id),
  CONSTRAINT uk_ats_categoria_nome UNIQUE (nome),
  CONSTRAINT ck_ats_categoria_nome CHECK (LENGTH(TRIM(nome)) BETWEEN 3 AND 80),
  CONSTRAINT ck_ats_categoria_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE ats_produto (
  produto_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  categoria_id  NUMBER NOT NULL,
  sku           VARCHAR2(20) NOT NULL,
  nome          VARCHAR2(120) NOT NULL,
  preco         NUMBER(12,2) NOT NULL,
  estoque       NUMBER(8) DEFAULT 0 NOT NULL,
  ativo         CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_ats_produto PRIMARY KEY (produto_id),
  CONSTRAINT uk_ats_produto_sku UNIQUE (sku),
  CONSTRAINT fk_ats_produto_categoria FOREIGN KEY (categoria_id) REFERENCES ats_categoria (categoria_id),
  CONSTRAINT ck_ats_produto_nome CHECK (LENGTH(TRIM(nome)) BETWEEN 3 AND 120),
  CONSTRAINT ck_ats_produto_preco CHECK (preco BETWEEN 0.01 AND 999999.99),
  CONSTRAINT ck_ats_produto_estoque CHECK (estoque BETWEEN 0 AND 99999999 AND estoque = TRUNC(estoque)),
  CONSTRAINT ck_ats_produto_ativo CHECK (ativo IN ('S', 'N'))
);

CREATE TABLE ats_pedido (
  pedido_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  cliente_id     NUMBER NOT NULL,
  endereco_id    NUMBER NOT NULL,
  data_pedido    DATE DEFAULT SYSDATE NOT NULL,
  status_pedido  VARCHAR2(12) DEFAULT 'ABERTO' NOT NULL,
  valor_total    NUMBER(12,2) NOT NULL,
  CONSTRAINT pk_ats_pedido PRIMARY KEY (pedido_id),
  CONSTRAINT uk_ats_pedido_id_total UNIQUE (pedido_id, valor_total),
  CONSTRAINT fk_ats_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES ats_cliente (cliente_id),
  CONSTRAINT fk_ats_pedido_end_cli FOREIGN KEY (endereco_id, cliente_id)
    REFERENCES ats_endereco (endereco_id, cliente_id),
  CONSTRAINT ck_ats_pedido_status CHECK (status_pedido IN ('ABERTO', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO')),
  CONSTRAINT ck_ats_pedido_total CHECK (valor_total BETWEEN 0 AND 9999999999.99)
);

CREATE TABLE ats_item_pedido (
  pedido_id           NUMBER NOT NULL,
  produto_id          NUMBER NOT NULL,
  quantidade          NUMBER(3) NOT NULL,
  preco_unitario      NUMBER(12,2) NOT NULL,
  desconto_percentual NUMBER(5,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_ats_item_pedido PRIMARY KEY (pedido_id, produto_id),
  CONSTRAINT fk_ats_item_pedido FOREIGN KEY (pedido_id) REFERENCES ats_pedido (pedido_id),
  CONSTRAINT fk_ats_item_produto FOREIGN KEY (produto_id) REFERENCES ats_produto (produto_id),
  CONSTRAINT ck_ats_item_qtd CHECK (quantidade BETWEEN 1 AND 999 AND quantidade = TRUNC(quantidade)),
  CONSTRAINT ck_ats_item_preco CHECK (preco_unitario BETWEEN 0.01 AND 999999.99),
  CONSTRAINT ck_ats_item_desconto CHECK (desconto_percentual BETWEEN 0 AND 100)
);

CREATE TABLE ats_pagamento (
  pagamento_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id         NUMBER NOT NULL,
  forma_pagamento   VARCHAR2(12) NOT NULL,
  valor             NUMBER(12,2) NOT NULL,
  parcelas          NUMBER(2) DEFAULT 1 NOT NULL,
  status_pagamento  VARCHAR2(12) DEFAULT 'PENDENTE' NOT NULL,
  data_pagamento    DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_ats_pagamento PRIMARY KEY (pagamento_id),
  CONSTRAINT uk_ats_pagamento_pedido UNIQUE (pedido_id),
  CONSTRAINT fk_ats_pagamento_pedido FOREIGN KEY (pedido_id) REFERENCES ats_pedido (pedido_id),
  CONSTRAINT fk_ats_pagamento_total FOREIGN KEY (pedido_id, valor)
    REFERENCES ats_pedido (pedido_id, valor_total),
  CONSTRAINT ck_ats_pagamento_forma CHECK (forma_pagamento IN ('PIX', 'CARTAO', 'BOLETO', 'DINHEIRO')),
  CONSTRAINT ck_ats_pagamento_valor CHECK (valor BETWEEN 0.01 AND 9999999999.99),
  CONSTRAINT ck_ats_pagamento_parc CHECK (parcelas BETWEEN 1 AND 12 AND parcelas = TRUNC(parcelas)),
  CONSTRAINT ck_ats_pagamento_status CHECK (status_pagamento IN ('PENDENTE', 'APROVADO', 'RECUSADO', 'ESTORNADO'))
);

CREATE TABLE ats_entrega (
  entrega_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  pedido_id        NUMBER NOT NULL,
  transportadora   VARCHAR2(80) NOT NULL,
  codigo_rastreio  VARCHAR2(40),
  status_entrega   VARCHAR2(12) DEFAULT 'PREPARANDO' NOT NULL,
  data_envio       DATE,
  data_prevista    DATE,
  data_entrega     DATE,
  CONSTRAINT pk_ats_entrega PRIMARY KEY (entrega_id),
  CONSTRAINT uk_ats_entrega_pedido UNIQUE (pedido_id),
  CONSTRAINT uk_ats_entrega_rastreio UNIQUE (codigo_rastreio),
  CONSTRAINT fk_ats_entrega_pedido FOREIGN KEY (pedido_id) REFERENCES ats_pedido (pedido_id),
  CONSTRAINT ck_ats_entrega_status CHECK (status_entrega IN ('PREPARANDO', 'ENVIADO', 'ENTREGUE', 'DEVOLVIDO')),
  CONSTRAINT ck_ats_entrega_prev CHECK (data_prevista IS NULL OR data_envio IS NULL OR data_prevista >= data_envio),
  CONSTRAINT ck_ats_entrega_data CHECK (data_entrega IS NULL OR (data_envio IS NOT NULL AND data_entrega >= data_envio)),
  CONSTRAINT ck_ats_entrega_concl CHECK (status_entrega <> 'ENTREGUE' OR data_entrega IS NOT NULL)
);

PROMPT Oito tabelas e suas restricoes criadas com sucesso.
